name: Format animations

on:
  pull_request:
    branches:
      - main
    paths:
      - animations/**/*.json

jobs:
  format-animations:
    name: Format animation JSONs

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.6

      - name: Cache NPM dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install NPM dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Format animation JSONs
        run: npm run build:clean

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🎨 Format animation JSONs
          file_pattern: animations/**/*.json
